obj-$(CONFIG_ARCH_NINTENDO3DS) += nintendo3ds_ctr.o
obj-$(CONFIG_ARCH_NINTENDO3DS) += bottom_lcd.o
obj-$(CONFIG_NINTENDO3DS_PXI) += pxi.o
obj-$(CONFIG_SMP) += platsmp.o
obj-$(CONFIG_SMP) += headsmp.o
